### ISSUE TITLE
Add a dropdown to select the "buyer-country" client-side parameter

### ISSUE THREAD

**Issue by CBoensel** [engenmt-pp/Alice#119]
See JS SDK docs for further details. 

This is relevant to test Vault from countries where it is not (yet) available -- without a VPN. 

See https://github.com/CBoensel/unload-paypal-button-demo / https://unload-paypal-button-demo.vercel.app/ for a demo of what I mean.

**Comment by engenmt-pp** [comment]
Hi Carsten! I've addressed this in PR https://github.com/engenmt-pp/Alice/pull/121. In particular, I've added all the supported countries that PayPal lists: https://github.com/engenmt-pp/Alice/blob/4504801ed159ef065ae945bcdb41b9d04f7932a0/src/templates/country-options.html
