### ISSUE TITLE
Support client-side button "label" parameter

### ISSUE THREAD

**Issue by CBoensel** [engenmt-pp/Alice#120]
This is to reflect the right button wording for `pay-now` vs `continue` flow. 

See `style.label` on https://developer.paypal.com/sdk/js/reference/#buttons. 

![image](https://github.com/engenmt-pp/Alice/assets/4338717/d1214146-5993-4a6d-af20-a8ec6719ba1b)

**Comment by engenmt-pp** [comment]
Hi Carsten, thanks for filing this! This was addressed in https://github.com/engenmt-pp/Alice/pull/121.
